# Generated by Django 3.1.1 on 2020-10-21 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='HP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_perf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.perfil')),
                ('nomb_hab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.habilidad')),
            ],
        ),
        migrations.AddField(
            model_name='habilidad',
            name='id_Perfil',
            field=models.ManyToManyField(related_name='HP', through='Usuario.HP', to='Usuario.Perfil'),
        ),
    ]
