# Generated by Django 3.1.1 on 2020-09-28 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='updateFoto'),
        ),
    ]
