# Generated by Django 3.1.1 on 2020-09-27 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='masBuscados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('puesto', models.CharField(max_length=50, verbose_name='Nombre')),
                ('id_Oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.oferta')),
            ],
        ),
    ]
