# Generated by Django 3.1.3 on 2020-11-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfhabs',
            name='precio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
