# Generated by Django 3.1.1 on 2020-09-26 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulacion',
            name='fecha_dos',
            field=models.DateField(blank=True, null=True, verbose_name='fecha dos'),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='fecha_tres',
            field=models.DateField(blank=True, null=True, verbose_name='fecha tres'),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='fecha_uno',
            field=models.DateField(blank=True, null=True, verbose_name='fecha uno'),
        ),
    ]
