# Generated by Django 3.1.1 on 2020-09-26 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_auto_20200925_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cv',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
