# Generated by Django 3.1.1 on 2020-10-21 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_auto_20201020_2359'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HP',
            new_name='HPer',
        ),
        migrations.AlterField(
            model_name='habilidad',
            name='id_Perfil',
            field=models.ManyToManyField(related_name='HPer', through='Usuario.HP', to='Usuario.Perfil'),
        ),
    ]
