# Generated by Django 3.1.1 on 2020-10-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_auto_20201007_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='updateFoto'),
        ),
    ]
