# Generated by Django 3.1.1 on 2020-09-28 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_curriculum_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curriculum',
            old_name='Experiencia',
            new_name='experiencia',
        ),
        migrations.RenameField(
            model_name='curriculum',
            old_name='Formación',
            new_name='formacion',
        ),
    ]
