# Generated by Django 3.1 on 2020-08-31 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0003_auto_20200831_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='fecha_de_ingreso',
            field=models.DateField(auto_now=True, verbose_name='Fecha de ingreso al sistema'),
        ),
    ]
